# Generated by Django 6.0.7 on 2026-07-09 21:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('syllabus', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grading_model', models.CharField(blank=True, choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=2, verbose_name='modelo de calificacion')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Abierto'), ('submitted', 'Enviado'), ('closed', 'Cerrado'), ('reopened', 'Reabierto'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de cierre')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de reapertura')),
                ('rule_version', models.CharField(default='S6.1', max_length=40, verbose_name='version de reglas')),
                ('course_section', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gradebook', to='enrollment.coursesection', verbose_name='curso/paralelo')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'libro de calificaciones',
                'verbose_name_plural': 'libros de calificaciones',
                'ordering': ['course_section__offer__period__code', 'course_section'],
            },
        ),
        migrations.CreateModel(
            name='GradeCalculationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_model', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=2, verbose_name='modelo')),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota final')),
                ('final_letter', models.CharField(max_length=1, verbose_name='letra final')),
                ('final_status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('recovery_required', 'Recuperacion requerida'), ('intersemestral', 'Intersemestral'), ('failed', 'Reprobado')], max_length=30, verbose_name='estado final')),
                ('failed_learning_outcomes_count', models.PositiveSmallIntegerField(default=0, verbose_name='resultados no alcanzados')),
                ('recovery_required', models.BooleanField(default=False, verbose_name='requiere recuperacion')),
                ('payload', models.JSONField(default=dict, verbose_name='detalle calculado')),
                ('rule_version', models.CharField(max_length=40, verbose_name='version de regla')),
                ('source', models.CharField(default='manual_recalculation', max_length=60, verbose_name='fuente')),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de calculo')),
                ('is_current', models.BooleanField(default=True, verbose_name='snapshot vigente')),
                ('calculated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_calculations', to=settings.AUTH_USER_MODEL, verbose_name='calculado por')),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_snapshots', to='enrollment.courseenrollment', verbose_name='matricula en curso')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_snapshots', to='grading.gradebook', verbose_name='libro de calificaciones')),
            ],
            options={
                'verbose_name': 'snapshot de calculo de nota',
                'verbose_name_plural': 'snapshots de calculo de notas',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('learning_outcome', 'Resultado de aprendizaje'), ('criterion', 'Criterio'), ('activity', 'Actividad'), ('recovery', 'Recuperacion'), ('partial', 'Parcial'), ('practice_activity', 'Actividad practica'), ('evaluation', 'Evaluacion'), ('final_evaluation', 'Evaluacion final')], max_length=30, verbose_name='tipo')),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='ponderacion')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='nota maxima')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grading.gradebook', verbose_name='libro de calificaciones')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grading.gradeitem', verbose_name='item padre')),
                ('syllabus_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_items', to='syllabus.syllabuscriterion', verbose_name='criterio del silabo')),
                ('syllabus_learning_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grade_items', to='syllabus.syllabuslearningoutcome', verbose_name='resultado de aprendizaje del silabo')),
            ],
            options={
                'verbose_name': 'item de calificacion',
                'verbose_name_plural': 'items de calificacion',
                'ordering': ['gradebook', 'parent_id', 'order'],
            },
        ),
        migrations.CreateModel(
            name='StudentGradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('50.00'))], verbose_name='nota')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('deleted', 'Eliminado logicamente')], default='active', max_length=20, verbose_name='estado')),
                ('reason', models.TextField(blank=True, verbose_name='justificacion')),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grade_records', to='enrollment.courseenrollment', verbose_name='matricula en curso')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_grade_records', to=settings.AUTH_USER_MODEL, verbose_name='ingresado por')),
                ('grade_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_records', to='grading.gradeitem', verbose_name='item de calificacion')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_records', to='grading.gradebook', verbose_name='libro de calificaciones')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_grade_records', to=settings.AUTH_USER_MODEL, verbose_name='actualizado por')),
            ],
            options={
                'verbose_name': 'registro de nota',
                'verbose_name_plural': 'registros de notas',
                'ordering': ['gradebook', 'course_enrollment', 'grade_item__order'],
            },
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['status'], name='grading_gra_status_d68456_idx'),
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['grading_model'], name='grading_gra_grading_aff4a1_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecalculationsnapshot',
            index=models.Index(fields=['grading_model', 'final_status'], name='grading_gra_grading_a3fa29_idx'),
        ),
        migrations.AddIndex(
            model_name='gradecalculationsnapshot',
            index=models.Index(fields=['calculated_at'], name='grading_gra_calcula_211346_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradecalculationsnapshot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('gradebook', 'course_enrollment'), name='unique_current_grade_snapshot_per_student'),
        ),
        migrations.AddConstraint(
            model_name='gradeitem',
            constraint=models.UniqueConstraint(fields=('gradebook', 'parent', 'item_type', 'order'), name='unique_grade_item_order_per_parent_type'),
        ),
        migrations.AddIndex(
            model_name='studentgraderecord',
            index=models.Index(fields=['status'], name='grading_stu_status_79e253_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentgraderecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('gradebook', 'course_enrollment', 'grade_item'), name='unique_active_grade_record_per_student_item'),
        ),
    ]
