# Generated by Django 6.0.7 on 2026-07-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_catalogs', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_code', models.CharField(max_length=30, unique=True, verbose_name='codigo docente')),
                ('academic_degree', models.CharField(blank=True, max_length=120, verbose_name='grado academico')),
                ('professional_title', models.CharField(blank=True, max_length=180, verbose_name='titulo profesional')),
                ('academic_profile', models.TextField(blank=True, verbose_name='perfil academico/profesional')),
                ('institutional_phone', models.CharField(blank=True, max_length=30, verbose_name='telefono institucional')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('invitado', 'Invitado'), ('codocente', 'Codocente'), ('externo', 'Externo')], default='activo', max_length=20, verbose_name='estado')),
                ('domains', models.ManyToManyField(blank=True, related_name='teachers', to='academic_catalogs.academicdomain', verbose_name='dominios o areas')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to='people.person', verbose_name='persona')),
            ],
            options={
                'verbose_name': 'docente',
                'verbose_name_plural': 'docentes',
                'ordering': ['person__last_name', 'person__first_name', 'teacher_code'],
            },
        ),
        migrations.CreateModel(
            name='TeacherOfficeHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modality', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=20, verbose_name='modalidad')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miercoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sabado'), (7, 'Domingo')], verbose_name='dia')),
                ('start_time', models.TimeField(verbose_name='hora inicio')),
                ('end_time', models.TimeField(verbose_name='hora fin')),
                ('location_or_link', models.CharField(max_length=255, verbose_name='lugar o enlace')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_hours', to='teachers.teacher', verbose_name='docente')),
            ],
            options={
                'verbose_name': 'horario de atencion docente',
                'verbose_name_plural': 'horarios de atencion docente',
                'ordering': ['teacher', 'day_of_week', 'start_time'],
            },
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_code'], name='teachers_te_teacher_1a54ad_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['status'], name='teachers_te_status_cc7a79_idx'),
        ),
        migrations.AddIndex(
            model_name='teacherofficehour',
            index=models.Index(fields=['teacher', 'day_of_week'], name='teachers_te_teacher_88aa5c_idx'),
        ),
    ]
