# Generated by Django 6.0.7 on 2026-07-09 16:31

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'dominio academico',
                'verbose_name_plural': 'dominios academicos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FacultyOrUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'unidad academica',
                'verbose_name_plural': 'unidades academicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuracion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'verbose_name': 'sistema de calificacion',
                'verbose_name_plural': 'sistemas de calificacion',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'modalidad',
                'verbose_name_plural': 'modalidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('start_date', models.DateField(verbose_name='fecha de inicio')),
                ('end_date', models.DateField(verbose_name='fecha de fin')),
                ('enrollment_start_date', models.DateField(verbose_name='inicio de matricula')),
                ('enrollment_end_date', models.DateField(verbose_name='fin de matricula')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('closed', 'Cerrado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('is_current', models.BooleanField(default=False, verbose_name='periodo actual')),
            ],
            options={
                'verbose_name': 'periodo academico',
                'verbose_name_plural': 'periodos academicos',
                'ordering': ['-start_date', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='unique_current_academic_period')],
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
                ('coordinator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_careers', to=settings.AUTH_USER_MODEL, verbose_name='coordinador')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='careers', to='academic_catalogs.academicdomain', verbose_name='dominio')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='careers', to='academic_catalogs.facultyorunit', verbose_name='unidad academica')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='careers', to='academic_catalogs.modality', verbose_name='modalidad')),
            ],
            options={
                'verbose_name': 'carrera',
                'verbose_name_plural': 'carreras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AcademicSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='nombre')),
                ('score_min', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='nota minima')),
                ('score_max', models.DecimalField(decimal_places=2, default=50, max_digits=5, verbose_name='nota maxima')),
                ('passing_score', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='umbral de aprobacion')),
                ('is_default', models.BooleanField(default=False, verbose_name='configuracion global por defecto')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='academic_catalogs.academicperiod', verbose_name='periodo')),
                ('career', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='academic_catalogs.career', verbose_name='carrera')),
                ('default_grading_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academic_settings', to='academic_catalogs.gradingsystem', verbose_name='sistema de calificacion por defecto')),
            ],
            options={
                'verbose_name': 'configuracion academica',
                'verbose_name_plural': 'configuraciones academicas',
                'ordering': ['-is_default', 'career__name', 'period__code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='codigo')),
                ('name', models.CharField(max_length=150, verbose_name='nombre')),
                ('version', models.CharField(max_length=40, verbose_name='version')),
                ('effective_from', models.DateField(verbose_name='vigente desde')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='vigente hasta')),
                ('is_current', models.BooleanField(default=False, verbose_name='plan vigente')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_plans', to='academic_catalogs.career', verbose_name='carrera')),
            ],
            options={
                'verbose_name': 'plan de estudio',
                'verbose_name_plural': 'planes de estudio',
                'ordering': ['career__name', '-effective_from', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AcademicLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='numero')),
                ('name', models.CharField(max_length=80, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='orden')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='academic_catalogs.studyplan', verbose_name='plan de estudio')),
            ],
            options={
                'verbose_name': 'nivel academico',
                'verbose_name_plural': 'niveles academicos',
                'ordering': ['study_plan', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30, verbose_name='codigo')),
                ('name', models.CharField(max_length=180, verbose_name='nombre')),
                ('total_hours', models.PositiveSmallIntegerField(verbose_name='horas totales')),
                ('contact_hours', models.PositiveSmallIntegerField(verbose_name='horas contacto docente')),
                ('autonomous_hours', models.PositiveSmallIntegerField(verbose_name='horas autonomas')),
                ('practical_hours', models.PositiveSmallIntegerField(verbose_name='horas practico-experimentales')),
                ('default_syllabus_version', models.CharField(choices=[('new', 'Nueva version'), ('legacy', 'Version anterior')], default='new', max_length=20, verbose_name='version de silabo por defecto')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('archived', 'Archivado')], default='active', max_length=20, verbose_name='estado')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic_catalogs.career', verbose_name='carrera')),
                ('default_grading_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='academic_catalogs.gradingsystem', verbose_name='sistema de calificacion por defecto')),
            ],
            options={
                'verbose_name': 'asignatura',
                'verbose_name_plural': 'asignaturas',
                'ordering': ['career__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='orden')),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='creditos')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_subjects', to='academic_catalogs.academicdomain', verbose_name='dominio')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_subjects', to='academic_catalogs.academiclevel', verbose_name='nivel')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_subjects', to='academic_catalogs.studyplan', verbose_name='plan de estudio')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='academic_catalogs.subject', verbose_name='asignatura')),
            ],
            options={
                'verbose_name': 'asignatura de malla',
                'verbose_name_plural': 'asignaturas de malla',
                'ordering': ['study_plan', 'level__order', 'order', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='AchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('letter', models.CharField(max_length=1, verbose_name='letra')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota minima')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='nota maxima')),
                ('description', models.CharField(max_length=180, verbose_name='descripcion')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_levels', to='academic_catalogs.academicsetting', verbose_name='configuracion')),
            ],
            options={
                'verbose_name': 'nivel de logro',
                'verbose_name_plural': 'niveles de logro',
                'ordering': ['setting', '-min_score'],
                'constraints': [models.UniqueConstraint(fields=('setting', 'letter'), name='unique_achievement_letter_per_setting')],
            },
        ),
        migrations.CreateModel(
            name='CurriculumPrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('curriculum_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='academic_catalogs.curriculumsubject', verbose_name='asignatura de malla')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by_links', to='academic_catalogs.curriculumsubject', verbose_name='prerrequisito')),
            ],
            options={
                'verbose_name': 'prerrequisito',
                'verbose_name_plural': 'prerrequisitos',
                'ordering': ['curriculum_subject', 'prerequisite'],
                'constraints': [models.UniqueConstraint(fields=('curriculum_subject', 'prerequisite'), name='unique_curriculum_prerequisite')],
            },
        ),
        migrations.AddConstraint(
            model_name='academicsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_academic_setting'),
        ),
        migrations.AddConstraint(
            model_name='academicsetting',
            constraint=models.UniqueConstraint(condition=models.Q(('career__isnull', False), ('period__isnull', False)), fields=('period', 'career'), name='unique_academic_setting_per_period_career'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(fields=('career', 'code'), name='unique_study_plan_code_per_career'),
        ),
        migrations.AddConstraint(
            model_name='studyplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('career', 'is_current'), name='unique_current_study_plan_per_career'),
        ),
        migrations.AddConstraint(
            model_name='academiclevel',
            constraint=models.UniqueConstraint(fields=('study_plan', 'number'), name='unique_level_number_per_study_plan'),
        ),
        migrations.AddConstraint(
            model_name='academiclevel',
            constraint=models.UniqueConstraint(fields=('study_plan', 'order'), name='unique_level_order_per_study_plan'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('career', 'code'), name='unique_subject_code_per_career'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('total_hours', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('contact_hours'), '+', models.F('autonomous_hours')), '+', models.F('practical_hours')))), name='subject_hours_match_total'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsubject',
            constraint=models.UniqueConstraint(fields=('study_plan', 'subject'), name='unique_subject_per_study_plan'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsubject',
            constraint=models.UniqueConstraint(fields=('study_plan', 'level', 'order'), name='unique_curriculum_order_per_level'),
        ),
    ]
