# Generated by Django 6.0.7 on 2026-07-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_catalogs', '0001_initial'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_code', models.CharField(max_length=30, unique=True, verbose_name='codigo estudiante')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='fecha de ingreso')),
                ('status', models.CharField(choices=[('aspirante_convertido', 'Aspirante convertido'), ('activo', 'Activo'), ('retirado', 'Retirado'), ('egresado', 'Egresado'), ('graduado', 'Graduado'), ('suspendido', 'Suspendido'), ('archivado', 'Archivado')], default='activo', max_length=30, verbose_name='estado')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('admission_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admitted_students', to='academic_catalogs.academicperiod', verbose_name='periodo de ingreso')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic_catalogs.career', verbose_name='carrera principal')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_profile', to='people.person', verbose_name='persona')),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academic_catalogs.studyplan', verbose_name='plan de estudio')),
            ],
            options={
                'verbose_name': 'estudiante',
                'verbose_name_plural': 'estudiantes',
                'ordering': ['person__last_name', 'person__first_name', 'student_code'],
                'indexes': [models.Index(fields=['student_code'], name='students_st_student_5e7a7e_idx'), models.Index(fields=['status'], name='students_st_status_5e2210_idx')],
            },
        ),
    ]
