# Generated by Django 6.0.7 on 2026-07-09 16:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identification_type', models.CharField(choices=[('cedula', 'Cedula'), ('passport', 'Pasaporte'), ('ruc', 'RUC'), ('other', 'Otro')], default='cedula', max_length=20, verbose_name='tipo de identificacion')),
                ('identification_number', models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='La identificacion solo puede contener letras, numeros, punto o guion.', regex='^[A-Za-z0-9\\-\\.]+$')], verbose_name='numero de identificacion')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('institutional_email', models.EmailField(blank=True, max_length=254, verbose_name='correo institucional')),
                ('personal_email', models.EmailField(blank=True, max_length=254, verbose_name='correo personal')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefono')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('address', models.TextField(blank=True, verbose_name='direccion')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['last_name', 'first_name', 'identification_number'],
                'indexes': [models.Index(fields=['identification_number'], name='people_pers_identif_149e8e_idx'), models.Index(fields=['last_name', 'first_name'], name='people_pers_last_na_c63c6e_idx'), models.Index(fields=['institutional_email'], name='people_pers_institu_8bbabd_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('identification_number__isnull', False), models.Q(('identification_number', ''), _negated=True)), fields=('identification_number',), name='unique_person_identification_when_present')],
            },
        ),
    ]
