# Generated by Django 6.0.7 on 2026-07-09 20:43

import apps.syllabus.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollment', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(choices=[('new', 'Nueva version'), ('legacy', 'Version anterior')], default='new', max_length=20, verbose_name='version')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('in_review', 'En revision'), ('approved', 'Aprobado'), ('observed', 'Observado'), ('finalized', 'Finalizado'), ('archived', 'Archivado')], default='draft', max_length=20, verbose_name='estado')),
                ('subject_description', models.TextField(blank=True, verbose_name='descripcion de la asignatura')),
                ('methodology', models.TextField(blank=True, verbose_name='metodologia')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalizacion')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de envio')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobacion')),
                ('signed_file', models.FileField(blank=True, upload_to=apps.syllabus.models.syllabus_signed_file_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='silabo firmado')),
                ('signed_file_uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de carga de archivo')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de archivo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('co_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='co_taught_syllabi', to='teachers.teacher', verbose_name='codocente')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='enrollment.coursesection', verbose_name='curso/paralelo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('lead_teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_syllabi', to='teachers.teacher', verbose_name='docente titular')),
                ('signed_file_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_signed_syllabi', to=settings.AUTH_USER_MODEL, verbose_name='archivo subido por')),
            ],
            options={
                'verbose_name': 'silabo',
                'verbose_name_plural': 'silabos',
                'ordering': ['-created_at', 'course_section__subject__code'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusBibliography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bibliography_type', models.CharField(choices=[('basic', 'Basica'), ('complementary', 'Complementaria'), ('recommended', 'Recomendada'), ('digital', 'Digital')], max_length=20, verbose_name='tipo')),
                ('apa_reference', models.TextField(verbose_name='referencia APA')),
                ('library_code', models.CharField(blank=True, max_length=80, verbose_name='codigo biblioteca')),
                ('copies', models.PositiveSmallIntegerField(default=0, verbose_name='cantidad de ejemplares')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'bibliografia de silabo',
                'verbose_name_plural': 'bibliografias de silabo',
                'ordering': ['syllabus', 'bibliography_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency_type', models.CharField(choices=[('transversal', 'Transversal'), ('disciplinary', 'Disciplinar')], max_length=20, verbose_name='tipo')),
                ('text', models.TextField(verbose_name='competencia')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'competencia de silabo',
                'verbose_name_plural': 'competencias de silabo',
                'ordering': ['syllabus', 'competency_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160, verbose_name='nombre')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='ponderacion')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'criterio de evaluacion de silabo',
                'verbose_name_plural': 'criterios de evaluacion de silabo',
                'ordering': ['learning_outcome', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusAchievementLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, verbose_name='nivel')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_levels', to='syllabus.syllabuscriterion', verbose_name='criterio')),
            ],
            options={
                'verbose_name': 'nivel de logro de silabo',
                'verbose_name_plural': 'niveles de logro de silabo',
                'ordering': ['criterion', 'level'],
            },
        ),
        migrations.CreateModel(
            name='SyllabusLearningOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outcome_type', models.CharField(choices=[('career', 'Carrera'), ('subject', 'Asignatura')], max_length=20, verbose_name='tipo')),
                ('code', models.CharField(blank=True, max_length=30, verbose_name='codigo')),
                ('text', models.TextField(verbose_name='resultado de aprendizaje')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='orden')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'resultado de aprendizaje de silabo',
                'verbose_name_plural': 'resultados de aprendizaje de silabo',
                'ordering': ['syllabus', 'outcome_type', 'order'],
            },
        ),
        migrations.AddField(
            model_name='syllabuscriterion',
            name='learning_outcome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='syllabus.syllabuslearningoutcome', verbose_name='resultado de aprendizaje'),
        ),
        migrations.CreateModel(
            name='SyllabusWeeklyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField(verbose_name='semana')),
                ('week_label', models.CharField(blank=True, max_length=80, verbose_name='etiqueta')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='fecha inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='fecha fin')),
                ('knowledge_dimension', models.CharField(max_length=160, verbose_name='dimension del conocimiento')),
                ('contact_strategy', models.TextField(blank=True, verbose_name='experiencia contacto docente')),
                ('contact_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='horas contacto docente')),
                ('contact_resources', models.TextField(blank=True, verbose_name='recursos contacto')),
                ('contact_scenarios', models.TextField(blank=True, verbose_name='escenarios contacto')),
                ('practical_strategy', models.TextField(blank=True, verbose_name='experiencia practico-experimental')),
                ('practical_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='horas practico-experimentales')),
                ('practical_resources', models.TextField(blank=True, verbose_name='recursos practicos')),
                ('practical_scenarios', models.TextField(blank=True, verbose_name='escenarios practicos')),
                ('autonomous_strategy', models.TextField(blank=True, verbose_name='experiencia autonoma')),
                ('autonomous_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='horas autonomas')),
                ('autonomous_resources', models.TextField(blank=True, verbose_name='recursos autonomos')),
                ('autonomous_scenarios', models.TextField(blank=True, verbose_name='escenarios autonomos')),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_plans', to='syllabus.syllabuslearningoutcome', verbose_name='resultado de aprendizaje')),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='syllabus.syllabus', verbose_name='silabo')),
            ],
            options={
                'verbose_name': 'planificacion semanal de silabo',
                'verbose_name_plural': 'planificaciones semanales de silabo',
                'ordering': ['syllabus', 'week_number'],
            },
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['status'], name='syllabus_sy_status_3b8930_idx'),
        ),
        migrations.AddIndex(
            model_name='syllabus',
            index=models.Index(fields=['version'], name='syllabus_sy_version_4b766d_idx'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'archived'), _negated=True), fields=('course_section',), name='unique_active_syllabus_per_course_section'),
        ),
        migrations.AddConstraint(
            model_name='syllabuscompetency',
            constraint=models.UniqueConstraint(fields=('syllabus', 'competency_type', 'order'), name='unique_syllabus_competency_order'),
        ),
        migrations.AddConstraint(
            model_name='syllabusachievementlevel',
            constraint=models.UniqueConstraint(fields=('criterion', 'level'), name='unique_syllabus_achievement_level'),
        ),
        migrations.AddConstraint(
            model_name='syllabuslearningoutcome',
            constraint=models.UniqueConstraint(fields=('syllabus', 'outcome_type', 'order'), name='unique_syllabus_learning_outcome_order'),
        ),
        migrations.AddConstraint(
            model_name='syllabuscriterion',
            constraint=models.UniqueConstraint(fields=('learning_outcome', 'order'), name='unique_syllabus_criterion_order'),
        ),
        migrations.AddConstraint(
            model_name='syllabusweeklyplan',
            constraint=models.UniqueConstraint(fields=('syllabus', 'week_number'), name='unique_syllabus_week_number'),
        ),
    ]
