# Generated by Django 6.0.7 on 2026-07-09 20:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_catalogs', '0001_initial'),
        ('students', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('published', 'Publicada'), ('closed', 'Cerrada'), ('archived', 'Archivada')], default='draft', max_length=20, verbose_name='estado')),
                ('description', models.TextField(blank=True, verbose_name='descripcion')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_offers', to='academic_catalogs.career', verbose_name='carrera')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_offers', to='academic_catalogs.academiclevel', verbose_name='nivel')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_offers', to='academic_catalogs.academicperiod', verbose_name='periodo')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_offers', to='academic_catalogs.studyplan', verbose_name='plan de estudio')),
            ],
            options={
                'verbose_name': 'oferta academica',
                'verbose_name_plural': 'ofertas academicas',
                'ordering': ['period__code', 'career__name', 'level__order'],
            },
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parallel', models.CharField(max_length=20, verbose_name='paralelo')),
                ('capacity', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='cupo')),
                ('classroom', models.CharField(blank=True, max_length=80, verbose_name='aula')),
                ('status', models.CharField(choices=[('planned', 'Planificado'), ('active', 'Activo'), ('closed', 'Cerrado'), ('canceled', 'Cancelado')], default='planned', max_length=20, verbose_name='estado')),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_sections', to='academic_catalogs.gradingsystem', verbose_name='sistema de calificacion')),
                ('modality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_sections', to='academic_catalogs.modality', verbose_name='modalidad')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_sections', to='enrollment.academicoffer', verbose_name='oferta academica')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_sections', to='academic_catalogs.subject', verbose_name='asignatura')),
            ],
            options={
                'verbose_name': 'curso/paralelo',
                'verbose_name_plural': 'cursos/paralelos',
                'ordering': ['offer', 'subject__code', 'parallel'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enrolled', 'Matriculado'), ('withdrawn', 'Retirado'), ('approved', 'Aprobado'), ('failed', 'Reprobado'), ('homologated', 'Homologado'), ('annulled', 'Anulado')], default='enrolled', max_length=20, verbose_name='estado')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic_catalogs.career', verbose_name='carrera')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic_catalogs.academicperiod', verbose_name='periodo')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.student', verbose_name='estudiante')),
                ('study_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic_catalogs.studyplan', verbose_name='plan de estudio')),
            ],
            options={
                'verbose_name': 'matricula academica',
                'verbose_name_plural': 'matriculas academicas',
                'ordering': ['-period__start_date', 'student__student_code'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('enrolled', 'Matriculado'), ('withdrawn', 'Retirado'), ('approved', 'Aprobado'), ('failed', 'Reprobado'), ('homologated', 'Homologado'), ('annulled', 'Anulado')], default='enrolled', max_length=20, verbose_name='estado')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de inscripcion')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de retiro')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_enrollments', to='enrollment.coursesection', verbose_name='curso/paralelo')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='enrollment.enrollment', verbose_name='matricula')),
            ],
            options={
                'verbose_name': 'matricula en curso',
                'verbose_name_plural': 'matriculas en curso',
                'ordering': ['enrollment', 'course_section__subject__code'],
            },
        ),
        migrations.CreateModel(
            name='Homologation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolution_reference', models.CharField(max_length=120, verbose_name='resolucion o referencia')),
                ('observations', models.TextField(blank=True, verbose_name='observaciones')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('registered', 'Registrada'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('annulled', 'Anulada')], default='registered', max_length=20, verbose_name='estado')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologations', to='academic_catalogs.academicperiod', verbose_name='periodo')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_homologations', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologations', to='students.student', verbose_name='estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='homologations', to='academic_catalogs.subject', verbose_name='asignatura')),
            ],
            options={
                'verbose_name': 'homologacion',
                'verbose_name_plural': 'homologaciones',
                'ordering': ['-created_at', 'student__student_code', 'subject__code'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('lead', 'Titular'), ('co_teacher', 'Codocente')], default='lead', max_length=20, verbose_name='rol docente')),
                ('weekly_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='carga horaria semanal')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo')], default='active', max_length=20, verbose_name='estado')),
                ('course_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='enrollment.coursesection', verbose_name='curso/paralelo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='teachers.teacher', verbose_name='docente')),
            ],
            options={
                'verbose_name': 'asignacion docente',
                'verbose_name_plural': 'asignaciones docentes',
                'ordering': ['course_section', 'role', 'teacher__person__last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='academicoffer',
            index=models.Index(fields=['status'], name='enrollment__status_64aa60_idx'),
        ),
        migrations.AddIndex(
            model_name='academicoffer',
            index=models.Index(fields=['period', 'career'], name='enrollment__period__bcfd8a_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicoffer',
            constraint=models.UniqueConstraint(fields=('period', 'career', 'study_plan', 'level'), name='unique_academic_offer_period_career_plan_level'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['status'], name='enrollment__status_2811e4_idx'),
        ),
        migrations.AddIndex(
            model_name='coursesection',
            index=models.Index(fields=['parallel'], name='enrollment__paralle_457fc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(fields=('offer', 'subject', 'parallel'), name='unique_course_section_offer_subject_parallel'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['status'], name='enrollment__status_c45c9d_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['period', 'career'], name='enrollment__period__6b0fad_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'period'), name='unique_enrollment_student_period'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['status'], name='enrollment__status_e994de_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('enrollment', 'course_section'), name='unique_course_enrollment_per_enrollment_course'),
        ),
        migrations.AddConstraint(
            model_name='homologation',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'period'), name='unique_homologation_student_subject_period'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(fields=('course_section', 'teacher', 'role'), name='unique_teacher_assignment_role_per_course'),
        ),
        migrations.AddConstraint(
            model_name='teachingassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'lead'), ('status', 'active')), fields=('course_section', 'role'), name='unique_active_lead_teacher_per_course'),
        ),
    ]
